name: Dart and Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      version:
        description: 'Flutter version to use'
        required: false
        type: string
        default: "stable"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Dart SDK version 3.1.5
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.0.2

      # Validate Flutter installation
      - name: Verify Flutter installation
        run: flutter doctor

      # Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Analyze the Flutter project
      - name: Analyze project
        run: flutter analyze

      # Format the code (with check if formatting is needed)
      - name: Check formatting
        run: dart format --set-exit-if-changed lib test integration_test

      # Run Flutter tests
      - name: Run Flutter tests
        run: flutter test

      # Run Dart tests (optional if there are separate Dart tests)
      - name: Run Dart tests
        run: dart test
